# [[items]]
# name = "Item Name"                     # Required: Display name
# size = 0.01                            # Required: Volume in mÂ³
# weight = 0.025                         # Required: Weight in kg

[[items]]
name = "Copper Coin"
size = 0.019
weight = 0.0025

[[items]]
name = "Iron Axe"
size = 0.0025
weight = 1.4

[[items]]
name = "Log"
size = 0.3
weight = 200

[[items]]
name = "Library Card"
size = 0.0001
weight = 0.005