# [[items]]
# name = "Item Name"                     # Required: Display name
# size = 0.01                            # Required: Volume in mÂ³
# weight = 0.025                         # Required: Weight in kg

[[items]]
name = "Copper Coin"
size = 0.019
weight = 0.0025