[[triggers]]
id = "first_field_visit"
priority = 1
effectType = "event"
effectData = "field_first_visit"
repeatable = false
[triggers.condition]
targetType = "location"
name = "Field"
operation = "visit"